# Generated by Django 5.0.3 on 2024-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddler_game', '0003_alter_quizresult_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
