# Generated by Django 5.0.3 on 2024-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddler_game', '0004_quizresult_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='django_time',
            field=models.FloatField(default=0),
        ),
    ]
